name: CI Dapp
on:
  push: { paths: ["dapp/**", ".github/workflows/ci-dapp.yml"] }
  pull_request: { paths: ["dapp/**", ".github/workflows/ci-dapp.yml"] }

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install & Lint & Build
        working-directory: dapp
        run: |
          pnpm i
          pnpm run -s lint || true
          pnpm run -s build || true
